### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Craig-Macomber** [mlo31415/FancyDownloader#2]
I realized no license is specified for this repo, leaving its contents under full copyright (plus github terms of service exceptions) by default.

Would you be willing to license this under some open source license, ensuring people's rights to use and modify it? I realize I have adapted your work without explicit permission (I got it fully working by the way, thanks for your help!), and would now like to, retroactively, secure this permission, as well as permission to redistribute my cleaned up version.

There is some guidance at https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Given the use-case for this script, I don't think the particular choice of license is too important. I personally like the MIT license since its simple.

Thanks!

**Comment by mlo31415** [comment]
Apologies for the delay, but you have given me enough to think about that I'm not going to dash off an answer.  As far as your own project goes, feel free to use FancyDownloader, HelpersPackage and anything of mine they depend on under the I-don’t-care-what-you-do-as-long-as-you-don’t-blame-me-if-it-doesn't-work-or-does-something-unexpected-and-if-you-give-me-credit sort of CC license. 

-- mlo

**Comment by Craig-Macomber** [comment]
Thanks! That is good enough for my use case!
